before_install: cd backend
language: node_js
node_js:
  - "stable"
cache: 
  directories:
    - "node_modules"
install:
  -npm install
script:
  -npm test
  -npm run build
deploy:
  github-token: $GITHUB_TOKEN
  on:
    branch: master